/* =============================================
   BLAZE KITCHEN — Sample Menu Data (120 Items)
   ============================================= */

const sampleMenuItems = [
  // ===== BURGERS (20 items) =====
  { name: "Classic Veggie Burger", description: "Fresh vegetable patty with lettuce, tomato, and special mayo", price: 199, category: "burgers", badge: "Popular", availability: true },
  { name: "Paneer Burger", description: "Golden fried paneer with crispy patty and cheese", price: 249, category: "burgers", badge: "New", availability: true },
  { name: "Chicken Burger Deluxe", description: "Juicy chicken patty with bacon, cheese, and caramelized onions", price: 299, category: "burgers", badge: "Bestseller", availability: true },
  { name: "Spicy Buffalo Burger", description: "Extra spicy chicken patty with buffalo sauce and blue cheese", price: 279, category: "burgers", badge: "Hot", availability: true },
  { name: "Tikka Masala Burger", description: "Grilled chicken tikka with yogurt mayo and cucumber", price: 269, category: "burgers", badge: "Indian", availability: true },
  { name: "Mediterranean Burger", description: "Feta cheese, olive tapenade, and roasted vegetables", price: 259, category: "burgers", badge: "", availability: true },
  { name: "Tandoori Chicken Burger", description: "Marinated tandoori chicken with mint chutney", price: 289, category: "burgers", badge: "Featured", availability: true },
  { name: "Mushroom Swiss Burger", description: "Grilled mushrooms with melted Swiss cheese", price: 239, category: "burgers", badge: "", availability: true },
  { name: "BBQ Bacon Burger", description: "Crispy bacon with smoky BBQ sauce and onion rings", price: 309, category: "burgers", badge: "Bestseller", availability: true },
  { name: "Rajwadi Mughlai Burger", description: "Keema patty with biryani spices and mint sauce", price: 279, category: "burgers", badge: "Royal", availability: true },
  { name: "Korean Gochujang Burger", description: "Spicy gochujang sauce with pickled vegetables", price: 289, category: "burgers", badge: "New", availability: true },
  { name: "Jalapeño Popper Burger", description: "Grilled jalapeños with cream cheese and ranch", price: 269, category: "burgers", badge: "Spicy", availability: true },
  { name: "Double Cheese Burger", description: "Double patty with triple layer of cheese", price: 349, category: "burgers", badge: "Power", availability: true },
  { name: "Smoky Chipotle Burger", description: "Chipotle mayo with grilled onions and crispy bacon", price: 289, category: "burgers", badge: "", availability: true },
  { name: "Peri Peri Chicken Burger", description: "Flame grilled with African hot spices", price: 279, category: "burgers", badge: "Hot", availability: true },
  { name: "Beetroot Black Bean Burger", description: "Healthy vegan option with beetroot and black beans", price: 229, category: "burgers", badge: "Vegan", availability: true },
  { name: "Tandoori Paneer Burger", description: "Tandoori marinated paneer with cucumber and mint", price: 259, category: "burgers", badge: "Vegetarian", availability: true },
  { name: "Sriracha Chicken Burger", description: "Spicy sriracha sauce with coleslaw", price: 279, category: "burgers", badge: "Trending", availability: true },
  { name: "Truffle Mushroom Burger", description: "Premium truffle oil with sautéed mushrooms", price: 349, category: "burgers", badge: "Premium", availability: true },
  { name: "Harissa Lamb Burger", description: "Spiced lamb patty with tahini and pomegranate", price: 319, category: "burgers", badge: "Middle East", availability: true },

  // ===== BEVERAGES (20 items) =====
  { name: "Fresh Orange Juice", description: "Freshly squeezed orange juice - 100% natural", price: 120, category: "beverages", badge: "", availability: true },
  { name: "Cold Brew Coffee", description: "Chilled strong coffee with a smooth, refreshing taste", price: 150, category: "beverages", badge: "", availability: true },
  { name: "Iced Green Tea", description: "Organic green tea with mint and honey", price: 100, category: "beverages", badge: "Healthy", availability: true },
  { name: "Strawberry Smoothie", description: "Creamy strawberry blend with yogurt and honey", price: 150, category: "beverages", badge: "Fresh", availability: true },
  { name: "Coconut Water", description: "Fresh coconut water - hydrating and natural", price: 80, category: "beverages", badge: "Natural", availability: true },
  { name: "Pomegranate Mocktail", description: "Refreshing pomegranate juice with sparkling water", price: 130, category: "beverages", badge: "", availability: true },
  { name: "Iced Lemon Tea", description: "Refreshing iced tea with fresh lemon juice", price: 100, category: "beverages", badge: "", availability: true },
  { name: "Blueberry Smoothie", description: "Antioxidant-rich blueberry yogurt smoothie", price: 160, category: "beverages", badge: "Healthy", availability: true },
  { name: "Passion Fruit Juice", description: "Exotic passion fruit juice with ice", price: 140, category: "beverages", badge: "Tropical", availability: true },
  { name: "Watermelon Cooler", description: "Refreshing watermelon juice with mint", price: 120, category: "beverages", badge: "Summer", availability: true },
  { name: "Pineapple Punch", description: "Tropical pineapple juice blend", price: 130, category: "beverages", badge: "", availability: true },
  { name: "Chilled Coffee", description: "Strong espresso served chilled", price: 140, category: "beverages", badge: "", availability: true },
  { name: "Lychee Lemonade", description: "Sweet lychee with fresh lemon juice", price: 130, category: "beverages", badge: "Exotic", availability: true },
  { name: "Guava Juice", description: "Fresh guava juice with pulp", price: 120, category: "beverages", badge: "", availability: true },
  { name: "Minted Cucumber Water", description: "Hydrating cucumber water with fresh mint", price: 90, category: "beverages", badge: "Detox", availability: true },
  { name: "Carrot Ginger Juice", description: "Healthy carrot and ginger juice", price: 120, category: "beverages", badge: "Detox", availability: true },
  { name: "Apple Cinnamon Smoothie", description: "Apple blended with cinnamon and yogurt", price: 150, category: "beverages", badge: "", availability: true },
  { name: "Mango Smoothie", description: "Creamy mango smoothie with yogurt", price: 140, category: "beverages", badge: "Popular", availability: true },
  { name: "Chocolate Shake", description: "Chocolate-flavored milk shake", price: 160, category: "beverages", badge: "Favorite", availability: true },

  // ===== APPETIZERS (20 items) =====
  { name: "Crispy Spring Rolls", description: "Golden fried spring rolls with sweet chili sauce", price: 149, category: "appetizers", badge: "Popular", availability: true },
  { name: "Garlic Bread", description: "Toasted bread with garlic butter and herbs", price: 99, category: "appetizers", badge: "", availability: true },
  { name: "Cheese Fries", description: "Crispy fries topped with melted cheese", price: 129, category: "appetizers", badge: "Favorite", availability: true },
  { name: "Paneer Tikka", description: "Grilled paneer cubes with tandoori spices", price: 179, category: "appetizers", badge: "Vegetarian", availability: true },
  { name: "Chicken Momos", description: "Steamed dumplings filled with spiced chicken", price: 159, category: "appetizers", badge: "Asian", availability: true },
  { name: "Samsa", description: "Crispy fried pastry with savory filling", price: 89, category: "appetizers", badge: "Traditional", availability: true },
  { name: "Buffalo Wings", description: "Spicy buffalo sauce with crispy chicken wings", price: 199, category: "appetizers", badge: "Spicy", availability: true },
  { name: "Vegetable Pakora", description: "Battered and fried mixed vegetables", price: 119, category: "appetizers", badge: "Vegan", availability: true },
  { name: "Chilli Garlic Noodles", description: "Crispy noodles with chilli and garlic", price: 139, category: "appetizers", badge: "", availability: true },
  { name: "Corn and Cheese Fritters", description: "Sweet corn fritters with cheese", price: 129, category: "appetizers", badge: "", availability: true },
  { name: "Spinach and Feta Pastry", description: "Crispy pastry with spinach and feta cheese", price: 149, category: "appetizers", badge: "Mediterranean", availability: true },
  { name: "Prawn Tempura", description: "Battered and fried prawn with dipping sauce", price: 189, category: "appetizers", badge: "Seafood", availability: true },
  { name: "Mushroom Tikka", description: "Marinated and grilled mushrooms", price: 169, category: "appetizers", badge: "Vegetarian", availability: true },
  { name: "Tandoori Chicken Skewers", description: "Grilled chicken skewers with yogurt marinade", price: 189, category: "appetizers", badge: "Grilled", availability: true },
  { name: "Fish Finger", description: "Crispy battered fish fingers", price: 179, category: "appetizers", badge: "Seafood", availability: true },
  { name: "Onion Rings", description: "Golden fried onion rings with ranch dip", price: 119, category: "appetizers", badge: "", availability: true },
  { name: "Broccoli Bites", description: "Crispy broccoli with cheese coating", price: 129, category: "appetizers", badge: "Healthy", availability: true },
  { name: "Seekh Kebab", description: "Minced meat kebab with spices", price: 179, category: "appetizers", badge: "Indian", availability: true },
  { name: "Veg Cutlet", description: "Mixed vegetable patty with spices", price: 99, category: "appetizers", badge: "Vegan", availability: true },
  { name: "Crispy Tofu Bites", description: "Golden fried tofu with sweet soy sauce", price: 149, category: "appetizers", badge: "Vegan", availability: true },

  // ===== COMBOS (20 items) =====
  { name: "Burger + Fries + Drink", description: "Complete meal: any burger, fries, and beverage", price: 399, category: "combos", badge: "Value Deal", availability: true },
  { name: "Chicken Combo", description: "Grilled chicken, rice, and soup", price: 349, category: "combos", badge: "Popular", availability: true },
  { name: "Paneer Delight Combo", description: "Paneer curry, naan, and raita", price: 329, category: "combos", badge: "Vegetarian", availability: true },
  { name: "Biryani + Raita + Dessert", description: "Fragrant biryani with yogurt and sweet", price: 399, category: "combos", badge: "Festive", availability: true },
  { name: "Pizza Combo", description: "1 Large pizza, sides, and drinks for 2", price: 499, category: "combos", badge: "Family", availability: true },
  { name: "Seafood Combo", description: "Grilled fish, prawns, and salad", price: 449, category: "combos", badge: "Seafood", availability: true },
  { name: "Vegetarian Special", description: "Dal, paneer, vegetables, and bread", price: 319, category: "combos", badge: "Vegan", availability: true },
  { name: "Spice Lover Combo", description: "Spicy curry, rice, and chutney", price: 349, category: "combos", badge: "Spicy", availability: true },
  { name: "Grilled Pack", description: "Tandoori chicken, paneer, and bread", price: 449, category: "combos", badge: "Grilled", availability: true },
  { name: "Friend's Special", description: "2 burgers, 2 fries, 2 drinks", price: 699, category: "combos", badge: "Duo Deal", availability: true },
  { name: "Breakfast Combo", description: "Eggs, toast, butter, and fresh juice", price: 249, category: "combos", badge: "Morning", availability: true },
  { name: "South Indian Combo", description: "Dosa, sambar, chutney, and coffee", price: 299, category: "combos", badge: "Traditional", availability: true },
  { name: "North Indian Combo", description: "Butter chicken, naan, and lassi", price: 399, category: "combos", badge: "Traditional", availability: true },
  { name: "Chinese Combo", description: "Hakka noodles, manchurian, and soup", price: 349, category: "combos", badge: "Asian", availability: true },
  { name: "Continental Combo", description: "Grilled vegetables, pasta, and sauce", price: 379, category: "combos", badge: "Western", availability: true },
  { name: "Dessert Combo", description: "3 different desserts for sharing", price: 449, category: "combos", badge: "Sweet", availability: true },
  { name: "Happy Meal (Kids)", description: "Junior burger, fries, drink, and toy", price: 199, category: "combos", badge: "Kids", availability: true },
  { name: "Premium Feast", description: "Steak, lobster tail, sides, and wine", price: 899, category: "combos", badge: "Premium", availability: true },
  { name: "Budget Meal", description: "2 items + 1 drink at special price", price: 249, category: "combos", badge: "Budget", availability: true },
  { name: "Weekend Party Pack", description: "4 burgers, 4 fries, 4 drinks", price: 999, category: "combos", badge: "Party", availability: true },

  // ===== COFFEE (20 items) =====
  { name: "Cappuccino", description: "Smooth espresso with steamed milk and foam", price: 150, category: "coffee", badge: "", availability: true },
  { name: "Espresso Shot", description: "Strong, concentrated shot of premium espresso", price: 100, category: "coffee", badge: "Quick", availability: true },
  { name: "Latte", description: "Creamy latte with velvety milk foam", price: 140, category: "coffee", badge: "", availability: true },
  { name: "Mocha", description: "Espresso, steamed milk, and chocolate", price: 160, category: "coffee", badge: "Favorite", availability: true },
  { name: "Macchiato", description: "Espresso marked with a small amount of milk", price: 130, category: "coffee", badge: "", availability: true },
  { name: "Americano", description: "Strong espresso diluted with hot water", price: 120, category: "coffee", badge: "", availability: true },
  { name: "Cortado", description: "Equal parts espresso and steamed milk", price: 140, category: "coffee", badge: "", availability: true },
  { name: "Flat White", description: "Smooth microfoam with velvety espresso", price: 150, category: "coffee", badge: "Premium", availability: true },
  { name: "Caramel Macchiato", description: "Macchiato with sweet caramel drizzle", price: 170, category: "coffee", badge: "Sweet", availability: true },
  { name: "Hazelnut Latte", description: "Latte infused with hazelnut flavor", price: 160, category: "coffee", badge: "", availability: true },
  { name: "Vanilla Cappuccino", description: "Cappuccino with vanilla syrup", price: 160, category: "coffee", badge: "", availability: true },
  { name: "Irish Coffee", description: "Coffee with Irish whiskey and cream", price: 200, category: "coffee", badge: "Adult", availability: true },
  { name: "Iced Cappuccino", description: "Chilled cappuccino served over ice", price: 160, category: "coffee", badge: "Iced", availability: true },
  { name: "Affogato", description: "Vanilla ice cream with hot espresso poured over", price: 140, category: "coffee", badge: "Dessert", availability: true },
  { name: "Long Black", description: "Double espresso with hot water", price: 130, category: "coffee", badge: "", availability: true },
  { name: "Turkish Coffee", description: "Strong traditional Turkish coffee", price: 120, category: "coffee", badge: "Traditional", availability: true },
  { name: "Vietnamese Coffee", description: "Strong coffee with condensed milk", price: 140, category: "coffee", badge: "Exotic", availability: true },


  // ===== DESSERTS (20 items) =====
  { name: "Chocolate Cake", description: "Rich and moist chocolate cake with ganache", price: 199, category: "desserts", badge: "Favorite", availability: true },
  { name: "Cheesecake Slice", description: "Creamy New York style cheesecake", price: 229, category: "desserts", badge: "Premium", availability: true },
  { name: "Vanilla Ice Cream Sundae", description: "Vanilla ice cream with chocolate sauce", price: 149, category: "desserts", badge: "", availability: true },
  { name: "Gulab Jamun", description: "Traditional Indian sweet dumplings", price: 99, category: "desserts", badge: "Traditional", availability: true },
  { name: "Brownie", description: "Fudgy chocolate brownie", price: 119, category: "desserts", badge: "", availability: true },
  { name: "Tiramisu", description: "Italian dessert with mascarpone and cocoa", price: 189, category: "desserts", badge: "Premium", availability: true },
  { name: "Crème Brûlée", description: "Creamy custard with caramelized sugar top", price: 209, category: "desserts", badge: "Elegant", availability: true },
  { name: "Carrot Cake", description: "Moist carrot cake with cream cheese frosting", price: 189, category: "desserts", badge: "", availability: true },
  { name: "Apple Pie", description: "Baked apple pie with cinnamon", price: 149, category: "desserts", badge: "", availability: true },
  { name: "Strawberry Cheesecake", description: "Cheesecake with fresh strawberry topping", price: 239, category: "desserts", badge: "Premium", availability: true },
  { name: "Kheer", description: "Traditional rice pudding with nuts and raisins", price: 79, category: "desserts", badge: "Traditional", availability: true },
  { name: "Rasgulla", description: "Soft cottage cheese balls in sugar syrup", price: 99, category: "desserts", badge: "Traditional", availability: true },
  { name: "Chocolate Lava Cake", description: "Warm chocolate cake with flowing center", price: 189, category: "desserts", badge: "Hot", availability: true },
  { name: "Fruit Tart", description: "Pastry with custard and fresh fruits", price: 179, category: "desserts", badge: "Fresh", availability: true },
  { name: "Jalebi", description: "Crispy spirals in sweet sugar syrup", price: 79, category: "desserts", badge: "Traditional", availability: true },

];

module.exports = sampleMenuItems;
